channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - catboost==1.2.2
    - scikit_learn==1.2.2
    - optuna==3.5.0
    - joblib==1.3.0
    - numpy==1.23.2
    - pandas==2.0.1
    - matplotlib==3.7.1
    - seaborn==0.13.1
    - pyyaml==6.0.1
    - psycopg2==2.9.9